// Package config loads and saves the outis configuration file.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
)

type SMTP struct {
	Host     string `toml:"host"`
	Port     int    `toml:"port"`
	Username string `toml:"username"`
}

type Config struct {
	// Domain of the addresses that should appear non-existent.
	Domain string `toml:"domain"`
	// MTAHost is the hostname the bounce claims to be generated by.
	MTAHost string `toml:"mta_host"`
	// EnvelopeFrom forces the SMTP envelope sender instead of trying the
	// null sender, MAILER-DAEMON@domain and the SMTP username in turn.
	EnvelopeFrom string `toml:"envelope_from,omitempty"`
	SMTP         SMTP   `toml:"smtp"`
}

// Path returns the config file location, honoring OUTIS_CONFIG.
func Path() (string, error) {
	if p := os.Getenv("OUTIS_CONFIG"); p != "" {
		return p, nil
	}
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "outis", "config.toml"), nil
}

func Load() (*Config, error) {
	p, err := Path()
	if err != nil {
		return nil, err
	}
	var c Config
	if _, err := toml.DecodeFile(p, &c); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("no config at %s, run `outis init`", p)
		}
		return nil, err
	}
	if c.SMTP.Port == 0 {
		c.SMTP.Port = 587
	}
	c.normalize()
	return &c, c.Validate()
}

// normalize accepts a full address in domain and keeps only the domain part.
func (c *Config) normalize() {
	if i := strings.LastIndex(c.Domain, "@"); i >= 0 {
		c.Domain = c.Domain[i+1:]
	}
	c.Domain = strings.ToLower(strings.TrimSpace(c.Domain))
}

func (c *Config) Validate() error {
	switch {
	case c.Domain == "":
		return errors.New("domain is required")
	case c.MTAHost == "":
		return errors.New("mta_host is required")
	case c.SMTP.Host == "":
		return errors.New("smtp.host is required")
	case c.SMTP.Username == "":
		return errors.New("smtp.username is required")
	}
	return nil
}

func (c *Config) Save() error {
	c.normalize()
	p, err := Path()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		return err
	}
	f, err := os.OpenFile(p, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	return toml.NewEncoder(f).Encode(c)
}
