// Package config loads and saves the outis configuration file.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
)

type SMTP struct {
	Host     string `toml:"host"`
	Port     int    `toml:"port"`
	Username string `toml:"username"`
}

type Account struct {
	// Domain of the addresses that should appear non-existent.
	Domain string `toml:"domain"`
	// MTAHost is the hostname the bounce claims to be generated by.
	MTAHost string `toml:"mta_host"`
	// EnvelopeFrom forces the SMTP envelope sender instead of trying the
	// null sender, MAILER-DAEMON@domain and the SMTP username in turn.
	EnvelopeFrom string `toml:"envelope_from,omitempty"`
	SMTP         SMTP   `toml:"smtp"`
}

type Config struct {
	// ReplyToFromDomains lists Return-Path domains whose bounces are sent to
	// the From header instead, e.g. providers with a shared suppression list.
	ReplyToFromDomains []string  `toml:"reply_to_from_domains"`
	Accounts           []Account `toml:"accounts"`
}

// DefaultReplyToFromDomains is used when the config does not set the list.
var DefaultReplyToFromDomains = []string{"amazonses.com"}

// legacy is the single-account layout used before multi-account support.
type legacy struct {
	Account
	ReplyToFromDomains []string  `toml:"reply_to_from_domains"`
	Accounts           []Account `toml:"accounts"`
}

// Path returns the config file location, honoring OUTIS_CONFIG.
func Path() (string, error) {
	if p := os.Getenv("OUTIS_CONFIG"); p != "" {
		return p, nil
	}
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "outis", "config.toml"), nil
}

func Load() (*Config, error) {
	p, err := Path()
	if err != nil {
		return nil, err
	}
	var l legacy
	if _, err := toml.DecodeFile(p, &l); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("no config at %s, run `outis init`", p)
		}
		return nil, err
	}
	c := &Config{Accounts: l.Accounts, ReplyToFromDomains: l.ReplyToFromDomains}
	if c.ReplyToFromDomains == nil {
		c.ReplyToFromDomains = DefaultReplyToFromDomains
	}
	if l.Domain != "" {
		c.Accounts = append([]Account{l.Account}, c.Accounts...)
	}
	for i := range c.Accounts {
		c.Accounts[i].normalize()
	}
	return c, c.Validate()
}

// Match returns the account whose domain matches one of the recipients.
func (c *Config) Match(recipients []string) (*Account, error) {
	var found []*Account
	for i := range c.Accounts {
		a := &c.Accounts[i]
		for _, r := range recipients {
			if strings.EqualFold(domainOf(r), a.Domain) {
				found = append(found, a)
				break
			}
		}
	}
	switch len(found) {
	case 1:
		return found[0], nil
	case 0:
		return nil, fmt.Errorf("none of the recipients (%s) matches a configured domain (%s), use --account",
			strings.Join(recipients, ", "), strings.Join(c.Domains(), ", "))
	default:
		var ds []string
		for _, a := range found {
			ds = append(ds, a.Domain)
		}
		return nil, fmt.Errorf("recipients match several accounts (%s), use --account", strings.Join(ds, ", "))
	}
}

// ReplyToFrom reports whether bounces for this Return-Path go to the From header.
func (c *Config) ReplyToFrom(returnPath string) bool {
	d := domainOf(returnPath)
	for _, s := range c.ReplyToFromDomains {
		if strings.EqualFold(d, s) || strings.HasSuffix(strings.ToLower(d), "."+strings.ToLower(s)) {
			return true
		}
	}
	return false
}

// Find returns the account for a domain, or nil.
func (c *Config) Find(domain string) *Account {
	for i := range c.Accounts {
		if strings.EqualFold(c.Accounts[i].Domain, domain) {
			return &c.Accounts[i]
		}
	}
	return nil
}

// Upsert replaces the account with the same domain or appends a new one.
func (c *Config) Upsert(a Account) {
	a.normalize()
	if cur := c.Find(a.Domain); cur != nil {
		*cur = a
		return
	}
	c.Accounts = append(c.Accounts, a)
}

func (c *Config) Domains() []string {
	ds := make([]string, 0, len(c.Accounts))
	for _, a := range c.Accounts {
		ds = append(ds, a.Domain)
	}
	return ds
}

func (c *Config) Validate() error {
	if len(c.Accounts) == 0 {
		return errors.New("no accounts configured, run `outis init`")
	}
	seen := map[string]bool{}
	for _, a := range c.Accounts {
		if err := a.Validate(); err != nil {
			return err
		}
		if seen[a.Domain] {
			return fmt.Errorf("domain %s configured twice", a.Domain)
		}
		seen[a.Domain] = true
	}
	return nil
}

func (c *Config) Save() error {
	if c.ReplyToFromDomains == nil {
		c.ReplyToFromDomains = DefaultReplyToFromDomains
	}
	p, err := Path()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		return err
	}
	f, err := os.OpenFile(p, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	return toml.NewEncoder(f).Encode(c)
}

// normalize accepts a full address in domain and keeps only the domain part.
func (a *Account) normalize() {
	a.Domain = strings.ToLower(strings.TrimSpace(domainOf(a.Domain)))
	if a.SMTP.Port == 0 {
		a.SMTP.Port = 587
	}
}

func (a *Account) Validate() error {
	switch {
	case a.Domain == "":
		return errors.New("domain is required")
	case a.MTAHost == "":
		return fmt.Errorf("%s: mta_host is required", a.Domain)
	case a.SMTP.Host == "":
		return fmt.Errorf("%s: smtp.host is required", a.Domain)
	case a.SMTP.Username == "":
		return fmt.Errorf("%s: smtp.username is required", a.Domain)
	}
	return nil
}

func domainOf(s string) string {
	if i := strings.LastIndex(s, "@"); i >= 0 {
		return s[i+1:]
	}
	return s
}
