// Package bounce builds RFC 3464 delivery status notifications that mimic
// a Postfix "unknown user" failure for a message that was already accepted.
package bounce

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/mail"
	"strings"
	"time"
)

// Original is the parsed inbound message the bounce refers to.
type Original struct {
	Raw        []byte
	Header     mail.Header
	ReturnPath string
	From       string
	MessageID  string
	Recipients []string
}

// Options control how the DSN is rendered.
type Options struct {
	// Domain is the local domain whose address "does not exist".
	Domain string
	// MTAHost is the hostname the bounce claims to be generated by.
	MTAHost string
	// Recipient overrides the automatically picked failed address.
	Recipient string
	// SendTo overrides the Return-Path as destination of the bounce.
	SendTo string
	Now    time.Time
}

// Result is a rendered bounce ready to be sent.
type Result struct {
	From string
	To   string
	// Redirected is true when To is not the original Return-Path.
	Redirected bool
	Recipient  string
	Message    []byte
}

// Parse reads a raw RFC 5322 message and extracts what the DSN needs.
func Parse(r io.Reader) (*Original, error) {
	raw, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}
	raw = normalizeCRLF(bytes.TrimLeft(raw, "\r\n"))
	msg, err := mail.ReadMessage(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("parse message: %w", err)
	}

	o := &Original{Raw: raw, Header: msg.Header}
	o.ReturnPath = firstAddress(msg.Header.Get("Return-Path"))
	if o.ReturnPath == "" {
		o.ReturnPath = firstAddress(msg.Header.Get("Sender"))
	}
	if o.ReturnPath == "" {
		o.ReturnPath = firstAddress(msg.Header.Get("From"))
	}
	if o.ReturnPath == "" {
		return nil, errors.New("no Return-Path, Sender or From header found")
	}
	o.From = firstAddress(msg.Header.Get("From"))
	o.MessageID = strings.TrimSpace(msg.Header.Get("Message-ID"))

	// Headers the sender wrote come first, then the envelope recipient before
	// alias expansion, so an alias is reported rather than the mailbox behind it
	for _, h := range []string{"To", "Cc", "X-Original-To", "X-Envelope-To", "Delivered-To"} {
		for _, v := range msg.Header[h] {
			o.Recipients = append(o.Recipients, allAddresses(v)...)
		}
	}
	return o, nil
}

// PickRecipient returns the first recipient at domain, else the first one seen.
func (o *Original) PickRecipient(domain string) (string, bool) {
	for _, r := range o.Recipients {
		if strings.EqualFold(domainOf(r), domain) {
			return r, true
		}
	}
	if len(o.Recipients) > 0 {
		return o.Recipients[0], false
	}
	return "", false
}

// Build renders the DSN for the given original message.
func Build(o *Original, opt Options) (*Result, error) {
	if opt.Domain == "" || opt.MTAHost == "" {
		return nil, errors.New("domain and mta host are required")
	}
	now := opt.Now
	if now.IsZero() {
		now = time.Now()
	}

	rcpt := opt.Recipient
	if rcpt == "" {
		var ok bool
		rcpt, ok = o.PickRecipient(opt.Domain)
		if rcpt == "" {
			return nil, errors.New("no recipient found in To/Cc, use --recipient")
		}
		if !ok {
			return nil, fmt.Errorf("none of the recipients (%s) is at domain %q, check `domain` in the config or use --recipient",
				strings.Join(o.Recipients, ", "), opt.Domain)
		}
	}
	local := rcpt[:strings.LastIndex(rcpt, "@")]

	qid := queueID()
	date := now.Format("Mon, 2 Jan 2006 15:04:05 -0700 (MST)")
	from := "MAILER-DAEMON@" + opt.Domain
	to := o.ReturnPath
	if opt.SendTo != "" {
		to = opt.SendTo
	}
	boundary := fmt.Sprintf("%s.%d/%s", qid, now.Unix(), opt.MTAHost)
	diag := fmt.Sprintf("unknown user: \"%s\"", local)

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\r\n", a...) }

	w("Received: by %s (Postfix)", opt.MTAHost)
	w("\tid %s; %s", qid, date)
	w("Date: %s", date)
	w("From: %s (Mail Delivery System)", from)
	w("Subject: Undelivered Mail Returned to Sender")
	w("To: %s", to)
	w("Auto-Submitted: auto-replied")
	w("MIME-Version: 1.0")
	w("Content-Type: multipart/report; report-type=delivery-status;")
	w("\tboundary=\"%s\"", boundary)
	w("Message-Id: <%s@%s>", qid, opt.MTAHost)
	if o.MessageID != "" {
		w("In-Reply-To: %s", o.MessageID)
		w("References: %s", o.MessageID)
	}
	w("")
	w("This is a MIME-encapsulated message.")
	w("")

	w("--%s", boundary)
	w("Content-Description: Notification")
	w("Content-Type: text/plain; charset=us-ascii")
	w("Content-Transfer-Encoding: 7bit")
	w("")
	w("This is the mail system at host %s.", opt.MTAHost)
	w("")
	w("I'm sorry to have to inform you that your message could not")
	w("be delivered to one or more recipients. It's attached below.")
	w("")
	w("For further assistance, please send mail to postmaster.")
	w("")
	w("If you do so, please include this problem report. You can")
	w("delete your own text from the attached returned message.")
	w("")
	w("                   The mail system")
	w("")
	w("<%s>: %s", rcpt, diag)
	w("")

	w("--%s", boundary)
	w("Content-Description: Delivery report")
	w("Content-Type: message/delivery-status")
	w("")
	w("Reporting-MTA: dns; %s", opt.MTAHost)
	w("X-Postfix-Queue-ID: %s", qid)
	w("X-Postfix-Sender: rfc822; %s", o.ReturnPath)
	w("Arrival-Date: %s", date)
	w("")
	w("Final-Recipient: rfc822; %s", rcpt)
	w("Original-Recipient: rfc822;%s", rcpt)
	w("Action: failed")
	w("Status: 5.1.1")
	w("Diagnostic-Code: x-unix; %s", diag)
	w("")

	w("--%s", boundary)
	w("Content-Description: Undelivered Message")
	w("Content-Type: message/rfc822")
	w("Content-Transfer-Encoding: 8bit")
	w("")
	b.Write(o.Raw)
	if !bytes.HasSuffix(o.Raw, []byte("\r\n")) {
		b.WriteString("\r\n")
	}
	w("--%s--", boundary)

	return &Result{
		From:       from,
		To:         to,
		Redirected: to != o.ReturnPath,
		Recipient:  rcpt,
		Message:    []byte(b.String()),
	}, nil
}

// queueID mimics a Postfix long queue ID: uppercase hex, digit first.
func queueID() string {
	var buf [6]byte
	rand.Read(buf[:])
	id := strings.ToUpper(hex.EncodeToString(buf[:]))
	return string('0'+buf[0]%10) + id[1:11]
}

func normalizeCRLF(b []byte) []byte {
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	return bytes.ReplaceAll(b, []byte("\n"), []byte("\r\n"))
}

func firstAddress(v string) string {
	as := allAddresses(v)
	if len(as) == 0 {
		return ""
	}
	return as[0]
}

func allAddresses(v string) []string {
	v = strings.TrimSpace(v)
	if v == "" {
		return nil
	}
	list, err := mail.ParseAddressList(v)
	if err != nil {
		// Return-Path may be a bare <addr>, fall back to trimming brackets
		v = strings.Trim(v, "<>")
		if strings.Contains(v, "@") {
			return []string{v}
		}
		return nil
	}
	out := make([]string, 0, len(list))
	for _, a := range list {
		out = append(out, a.Address)
	}
	return out
}

func domainOf(addr string) string {
	i := strings.LastIndex(addr, "@")
	if i < 0 {
		return ""
	}
	return addr[i+1:]
}
